#!/bin/sh

MODDIR=/data/adb/modules/RiProG
LOGFILE=/data/media/0/Android/AI.log
CPUDIR=/sys/devices/system/cpu
GPUDIR=/sys/kernel/gpu
KGSLDIR=/sys/class/kgsl

MODE=/data/adb/modules/RiProG/mode.txt

read_file() {
  if [ -f "$1" ]; then
    if [ ! -r "$1" ]; then
      chmod +r "$1"
    fi
    cat "$1"
  fi
}

write_file() {
  if [ -f "$1" ]; then
    if [ ! -w "$1" ]; then
      chmod +w "$1"
    fi
    echo "$2" > "$1"
  fi
}

if [ -d "$CPUDIR/cpu0" ]; then
  min_freq_0=$(read_file "$CPUDIR/cpu0/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | head -n 1)
  max_freq_0=$(read_file "$CPUDIR/cpu0/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | tail -n 1)
fi
if [ -d "$CPUDIR/cpu1" ]; then
  min_freq_1=$(read_file "$CPUDIR/cpu1/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | head -n 1)
  max_freq_1=$(read_file "$CPUDIR/cpu1/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | tail -n 1)
fi
if [ -d "$CPUDIR/cpu2" ]; then
  min_freq_2=$(read_file "$CPUDIR/cpu2/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | head -n 1)
  max_freq_2=$(read_file "$CPUDIR/cpu2/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | tail -n 1)
fi
if [ -d "$CPUDIR/cpu3" ]; then
  min_freq_3=$(read_file "$CPUDIR/cpu3/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | head -n 1)
  max_freq_3=$(read_file "$CPUDIR/cpu3/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | tail -n 1)
fi
if [ -d "$CPUDIR/cpu4" ]; then
  min_freq_4=$(read_file "$CPUDIR/cpu4/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | head -n 1)
  max_freq_4=$(read_file "$CPUDIR/cpu4/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | tail -n 1)
fi
if [ -d "$CPUDIR/cpu5" ]; then
  min_freq_5=$(read_file "$CPUDIR/cpu5/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | head -n 1)
  max_freq_5=$(read_file "$CPUDIR/cpu5/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | tail -n 1)
fi
if [ -d "$CPUDIR/cpu6" ]; then
  min_freq_6=$(read_file "$CPUDIR/cpu6/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | head -n 1)
  max_freq_6=$(read_file "$CPUDIR/cpu6/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | tail -n 1)
fi
if [ -d "$CPUDIR/cpu7" ]; then
  min_freq_7=$(read_file "$CPUDIR/cpu7/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | head -n 1)
  max_freq_7=$(read_file "$CPUDIR/cpu7/cpufreq/scaling_available_frequencies" | tr " " "\n" | sort -n | sed '/^$/d' | tail -n 1)
fi

min_clock_gpu=$(read_file "$KGSLDIR/gpu_freq_table" | tr " " "\n" | sort -n | sed '/^$/d' | head -n 1)
max_clock_gpu=$(read_file "$KGSLDIR/gpu_freq_table" | tr " " "\n" | sort -n | sed '/^$/d' | tail -n 1)

min_clock_kgsl=$(read_file "$KGSLDIR/kgsl-3d0/freq_table_mhz" | tr " " "\n" | sort -n | sed '/^$/d' | head -n 1)
max_clock_kgsl=$(read_file "$KGSLDIR/kgsl-3d0/freq_table_mhz" | tr " " "\n" | sort -n | sed '/^$/d' | tail -n 1)


game_list_filter=$(awk '!/ / {print "-e", $0}' "$MODDIR/gamelist.txt")

printf "" > "$LOGFILE"

echo "unset" > $MODE 

while true; do
  mode_apply=$(cat $MODE)
  
  sleep 2

 window=$(dumpsys window)
 gamestart=$(echo "$window" | grep -E 'mCurrentFocus|mFocusedApp' | grep "$game_list_filter")
 screenoff=$(echo "$window" | grep mScreen | grep false)

  sleep 2

    if [ "$gamestart" ]; then
      if [ ! "$mode_apply" = "game" ]; then

        sleep 2

        printf "game" > $MODE
        date >> $LOGFILE

        sleep 2
         
        write_file "/sys/module/lowmemorykiller/parameters/minfree" "2560,4096,8192,12288,16384,20480"

        for queue in /sys/block/mmcblk*/queue; do
          write_file "$queue/add_random" "0"
          write_file "$queue/iostats" "0"
          write_file "$queue/read_ahead_kb" "256"
          write_file "$queue/nr_requests" "128"
       done

        write_file "$CPUDIR/cpu0/cpufreq/scaling_min_freq" "$max_freq_0"
        write_file "$CPUDIR/cpu0/cpufreq/scaling_max_freq" "$max_freq_0"
        write_file "$CPUDIR/cpu1/cpufreq/scaling_min_freq" "$max_freq_1"
        write_file "$CPUDIR/cpu1/cpufreq/scaling_max_freq" "$max_freq_1"
        write_file "$CPUDIR/cpu2/cpufreq/scaling_min_freq" "$max_freq_2"
        write_file "$CPUDIR/cpu2/cpufreq/scaling_max_freq" "$max_freq_2"
        write_file "$CPUDIR/cpu3/cpufreq/scaling_min_freq" "$max_freq_3"
        write_file "$CPUDIR/cpu3/cpufreq/scaling_max_freq" "$max_freq_3"
        write_file "$CPUDIR/cpu4/cpufreq/scaling_min_freq" "$max_freq_4"
        write_file "$CPUDIR/cpu4/cpufreq/scaling_max_freq" "$max_freq_4"
        write_file "$CPUDIR/cpu5/cpufreq/scaling_min_freq" "$max_freq_5"
        write_file "$CPUDIR/cpu5/cpufreq/scaling_max_freq" "$max_freq_5"
        write_file "$CPUDIR/cpu6/cpufreq/scaling_min_freq" "$max_freq_6"
        write_file "$CPUDIR/cpu6/cpufreq/scaling_max_freq" "$max_freq_6"
        write_file "$CPUDIR/cpu7/cpufreq/scaling_min_freq" "$max_freq_7"
        write_file "$CPUDIR/cpu7/cpufreq/scaling_max_freq" "$max_freq_7"

        write_file "$GPUDIR/gpu_min_clock" "$max_clock_gpu"
        write_file "$GPUDIR/gpu_max_clock" "$max_clock_gpu"

        write_file "$KGSLDIR/kgsl-3d0/min_clock_mhz" "$max_clock_kgsl"
        write_file "$KGSLDIR/kgsl-3d0/max_clock_mhz" "$max_clock_kgsl"

        write_file "$KGSLDIR/kgsl-3d0/throttling" "0"

        echo "RiProG AI: Game Mode" >> $LOGFILE
        echo "" >> $LOGFILE
      fi

    elif [ "$screenoff" ]; then
      if [ ! "$mode_apply" = "sleep" ]; then

        sleep 2

        printf "sleep" > $MODE
        date >> $LOGFILE

        sleep 2

        write_file "/sys/module/lowmemorykiller/parameters/minfree" "128,256,1024,2048,4096,8192"

       for queue in /sys/block/mmcblk*/queue; do
          write_file "$queue/add_random" "0"
          write_file "$queue/iostats" "0"
          write_file "$queue/read_ahead_kb" "64"
          write_file "$queue/nr_requests" "16"
       done

        write_file "$CPUDIR/cpu0/cpufreq/scaling_min_freq" "$min_freq_0"
        write_file "$CPUDIR/cpu0/cpufreq/scaling_max_freq" "$min_freq_0"
        write_file "$CPUDIR/cpu1/cpufreq/scaling_min_freq" "$min_freq_1"
        write_file "$CPUDIR/cpu1/cpufreq/scaling_max_freq" "$min_freq_1"
        write_file "$CPUDIR/cpu2/cpufreq/scaling_min_freq" "$min_freq_2"
        write_file "$CPUDIR/cpu2/cpufreq/scaling_max_freq" "$min_freq_2"
        write_file "$CPUDIR/cpu3/cpufreq/scaling_min_freq" "$min_freq_3"
        write_file "$CPUDIR/cpu3/cpufreq/scaling_max_freq" "$min_freq_3"
        write_file "$CPUDIR/cpu4/cpufreq/scaling_min_freq" "$min_freq_4"
        write_file "$CPUDIR/cpu4/cpufreq/scaling_max_freq" "$min_freq_4"
        write_file "$CPUDIR/cpu5/cpufreq/scaling_min_freq" "$min_freq_5"
        write_file "$CPUDIR/cpu5/cpufreq/scaling_max_freq" "$min_freq_5"
        write_file "$CPUDIR/cpu6/cpufreq/scaling_min_freq" "$min_freq_6"
        write_file "$CPUDIR/cpu6/cpufreq/scaling_max_freq" "$min_freq_6"
        write_file "$CPUDIR/cpu7/cpufreq/scaling_min_freq" "$min_freq_7"
        write_file "$CPUDIR/cpu7/cpufreq/scaling_max_freq" "$min_freq_7"
  
        write_file "$GPUDIR/gpu_min_clock" "$max_clock_gpu"
        write_file "$GPUDIR/gpu_max_clock" "$max_clock_gpu"
        
        write_file "$KGSLDIR/kgsl-3d0/min_clock_mhz" "$min_clock_kgsl"
        write_file "$KGSLDIR/kgsl-3d0/max_clock_mhz" "$min_clock_kgsl"
  
        write_file "$KGSLDIR/kgsl-3d0/throttling" "1"
          
        echo "RiProG AI: Sleep Mode" >> $LOGFILE
        echo "" >> $LOGFILE
      fi

    else
      if [ ! "$mode_apply" = "daily" ]; then

        sleep 2

        printf "daily" > $MODE
        date >> $LOGFILE

        sleep 2

        write_file "/sys/module/lowmemorykiller/parameters/minfree" "2560,5120,7680,8960,10240,12800"

       for queue in /sys/block/mmcblk*/queue; do
          write_file "$queue/add_random" "0"
          write_file "$queue/iostats" "0"
          write_file "$queue/read_ahead_kb" "128"
          write_file "$queue/nr_requests" "32"
       done

        write_file "$CPUDIR/cpu0/cpufreq/scaling_min_freq" "$min_freq_0"
        write_file "$CPUDIR/cpu0/cpufreq/scaling_max_freq" "$max_freq_0"
        write_file "$CPUDIR/cpu1/cpufreq/scaling_min_freq" "$min_freq_1"
        write_file "$CPUDIR/cpu1/cpufreq/scaling_max_freq" "$max_freq_1"
        write_file "$CPUDIR/cpu2/cpufreq/scaling_min_freq" "$min_freq_2"
        write_file "$CPUDIR/cpu2/cpufreq/scaling_max_freq" "$max_freq_2"
        write_file "$CPUDIR/cpu3/cpufreq/scaling_min_freq" "$min_freq_3"
        write_file "$CPUDIR/cpu3/cpufreq/scaling_max_freq" "$max_freq_3"
        write_file "$CPUDIR/cpu4/cpufreq/scaling_min_freq" "$min_freq_4"
        write_file "$CPUDIR/cpu4/cpufreq/scaling_max_freq" "$max_freq_4"
        write_file "$CPUDIR/cpu5/cpufreq/scaling_min_freq" "$min_freq_5"
        write_file "$CPUDIR/cpu5/cpufreq/scaling_max_freq" "$max_freq_5"
        write_file "$CPUDIR/cpu6/cpufreq/scaling_min_freq" "$min_freq_6"
        write_file "$CPUDIR/cpu6/cpufreq/scaling_max_freq" "$max_freq_6"
        write_file "$CPUDIR/cpu7/cpufreq/scaling_min_freq" "$min_freq_7"
        write_file "$CPUDIR/cpu7/cpufreq/scaling_max_freq" "$max_freq_7"

        write_file "$GPUDIR/gpu_min_clock" "$min_clock_gpu"
        write_file "$GPUDIR/gpu_max_clock" "$max_clock_gpu"
          
        write_file "$KGSLDIR/kgsl-3d0/min_clock_mhz" "$min_clock_kgsl"
        write_file "$KGSLDIR/kgsl-3d0/max_clock_mhz" "$max_clock_kgsl"

        write_file "$KGSLDIR/kgsl-3d0/throttling" "1"

        echo "RiProG AI: Daily Mode" >> $LOGFILE
        echo "" >> $LOGFILE
      fi
    fi

  sleep 2

done