#!/sbin/sh

umask 022

ui_print() { echo "$1"; }

require_new_magisk() {
  ui_print ""
  ui_print " Please install Magisk v20.4+! "
  ui_print ""
  exit 1
}

OUTFD=$2; ZIPFILE=$3; mount /data 2>/dev/null

[ -f /data/adb/magisk/util_functions.sh ] || require_new_magisk
. /data/adb/magisk/util_functions.sh; [ $MAGISK_VER_CODE -lt 20400 ] && require_new_magisk

ui_print ""
ui_print "   RiProG Open Source @ RiOpSo   "
ui_print ""

BX1=$(which busybox)
BX2=$(command -v busybox)
BD1=$(find /system/*bin*/busybox)
BD2=$(find /data/adb/*modules*/*/system/bin/busybox)
if [[ -z "$BX1" ]] && [[ -z "$BX2" ]] && [[ -z "$BD1" ]] && [[ -z "$BD2" ]]; then
echo ""
    echo "Warning: Busybox not found"
    echo "The module will not work properly"
echo ""
    echo "Ignore if already installed"
echo ""
fi

install_module
exit 0