#!/bin/sh
android_properties="
persist.sys.dalvik.hyperthreading=true
persist.sys.dalvik.multithread=true
ro.hwui.texture_cache_size=128
ro.hwui.layer_cache_size=64
ro.hwui.r_buffer_cache_size=16
ro.hwui.path_cache_size=64
ro.hwui.gradient_cache_size=2
ro.hwui.drop_shadow_cache_size=8
ro.hwui.texture_cache_flushrate=0.2
ro.hwui.text_small_cache_width=2048
ro.hwui.text_small_cache_height=2048
ro.hwui.text_large_cache_width=4096
ro.hwui.text_large_cache_height=4096
ro.iorapd.enable=false
iorapd.perfetto.enable=false
iorapd.readahead.enable=false
persist.device_config.runtime_native_boot.iorap_readahead_enable=false
persist.sys.purgeable_assets=1
ro.media.dec.aud.flac.enabled=1
ro.media.dec.aud.wma.enabled=1
ro.media.dec.vid.avi.enabled=1
ro.media.dec.vid.wmv.enabled=1
ro.media.dec.aud.wma.enabled=1
ro.media.dec.aud.mp3.enabled=1
ro.media.dec.vid.mp4.enabled=1
ro.media.dec.aud.flac.enabled=1
ro.media.dec.vid.H.264.enabled=1
ro.media.enc.aud.flac.enabled=1
ro.media.enc.vid.H.264.enabled=1
ro.media.enc.aud.wma.enabled=1
ro.media.enc.vid.wmv.enabled=1
ro.media.enc.aud.mp3.enabled=1
ro.media.enc.vid.mp4.enabled=1
media.stagefright.enable-player=true
media.stagefright.enable-meta=true
media.stagefright.enable-scan=true
media.stagefright.enable-http=true
media.stagefright.enable-rtsp=true
media.stagefright.enable-record=false
"
echo "$android_properties" | while IFS= read -r prop; do
    prop_name="${prop%%=*}"
    prop_value="${prop#*=}"
    setprop"$prop_name" "$prop_value"
done
